"""drop stale ide_port index

Revision ID: 15af4faf772c
Revises: 0005_browser_sessions
Create Date: 2026-04-13 14:52:38.325855

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '15af4faf772c'
down_revision: Union[str, Sequence[str], None] = '0005_browser_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_ide_port'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspaces_ide_port'), 'workspaces', ['ide_port'], unique=False)
    # ### end Alembic commands ###
