"""Interactive configuration wizard.

Walks the user through every required + optional Field declared in
``spec.FIELDS``, runs validators, fills auto-generated values, writes the
result atomically to ``.env``.  Non-interactive mode reads everything
from existing env (process env or current ``.env``) and fails fast on
the first required-but-missing field.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Iterable

from . import env_io, spec
from .spec import Field
from .validators import ValidationResult


def _try_questionary():
    try:
        import questionary  # type: ignore
        return questionary
    except ImportError:
        return None


def _print_validation(result: ValidationResult, prefix: str = "  → ") -> None:
    icon = {"ok": "✓", "warn": "⚠", "fail": "✗"}[result.status]
    print(f"{prefix}{icon} {result.detail}", file=sys.stderr)


def _resolve_default(field: Field, current_env: dict[str, str]) -> str:
    """Return the value to pre-fill the prompt with: existing > field default > "" """
    existing = current_env.get(field.key, "").strip()
    if existing:
        return existing
    return spec.runtime_default(field) or ""


def _ask_one(field: Field, current_env: dict[str, str]):
    """Prompt for one field via questionary; returns the (validated) value
    or None if the user cancelled."""
    q = _try_questionary()
    if q is None:
        raise RuntimeError(
            "questionary not available — install via uv (`uv run scripts/up.py`) "
            "or run with --non-interactive"
        )
    default = _resolve_default(field, current_env)
    label = f"{field.key}\n  {field.help}"
    while True:
        if field.secret:
            answer = q.password(
                label,
                default=default if not default else "",
            ).ask()
        else:
            answer = q.text(label, default=default).ask()
        if answer is None:
            return None
        answer = answer.strip()
        # Empty + has default → use default.  Empty + no default + required
        # → re-prompt.
        if not answer and default:
            answer = default
        if not answer and field.required:
            print(f"  → field {field.key} is required, please enter a value", file=sys.stderr)
            continue
        if field.validator and answer:
            tentative_env = {**current_env, field.key: answer}
            result = field.validator(answer, tentative_env)
            _print_validation(result)
            if result.status == "fail":
                # Let user retry
                continue
        return answer


def run_wizard(
    *,
    env_path: Path,
    only_missing: bool = True,
    interactive: bool = True,
) -> dict[str, str]:
    """Drive the configuration walkthrough.

    Args:
      env_path: Path to ``.env``.  Read for current values; written at end.
      only_missing: When True, prompt only for fields that lack a non-empty
        value already.  When False, prompt for every field in ``FIELDS``.
      interactive: When False, take values entirely from existing env;
        fail fast if any required field is missing.

    Returns the final merged env dict (also written to ``env_path``).
    """
    current = env_io.read(env_path)
    # Process env (e.g. user exported CF_DNS_API_TOKEN before running) takes
    # priority over the file when seeding defaults — feels less surprising.
    for k in [f.key for f in spec.FIELDS]:
        if os.environ.get(k):
            current.setdefault(k, os.environ[k])

    if not interactive:
        missing = [
            k for k in spec.required_keys(current) if not current.get(k, "").strip()
        ]
        if missing:
            print(
                f"non-interactive: missing required env keys: {missing}",
                file=sys.stderr,
            )
            raise SystemExit(2)
    else:
        for field in spec.FIELDS:
            if only_missing and current.get(field.key, "").strip():
                # Already populated — silently keep.  --reconfigure
                # (only_missing=False) forces the prompt anyway.
                continue
            value = _ask_one(field, current)
            if value is None:
                # User cancelled (Ctrl+C / Esc).  Bail out without touching .env.
                print("aborted", file=sys.stderr)
                raise SystemExit(130)
            current[field.key] = value

    # Fill auto-generated blanks (SESSION_SECRET).
    for k, v in spec.autogenerate_blank(current).items():
        current[k] = v
        print(f"  → autogenerated {k} ({len(v)}-char hex)", file=sys.stderr)

    env_io.write(env_path, current)
    print(f"wrote {env_path} ({len(current)} keys)", file=sys.stderr)
    return current
